### ISSUE TITLE
Compatibility issues using Angular 6

### ISSUE THREAD

**Issue by CarlosTorrecillas** [jodit/jodit-angular#17] opened 2018-10-15 14:26 UTC
I think the package cannot be used yet with Angular 6.X. I got the following error when trying to install it:

```
ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/jodit-angular/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
```

Is there any chance you can publish a new version with the dependencies updated?

Thanks!

**Comment by helix46** [comment] 2018-10-15 23:04
Duplicate of #13 

Work around...
I've had to delete the node_modules folder so often that I've made a script to go in package.json scripts:

"fix-jodit-node-modules": "fix-jodit-node-modules.bat",

Contents of fix-jodit-node-modules.bat (for windows of course):
IF EXIST .\node_modules\jodit-angular\node_modules (
rd .\node_modules\jodit-angular\node_modules /S /q
)

**Comment by Raiper34** [comment] 2018-10-23 21:04
Same here...
`node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/jodit-angular/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.`

**Comment by Raiper34** [comment] 2018-11-18 22:31
Same for Angular 7...

**Comment by Scobee** [comment] 2019-01-20 22:23
@Raiper34  - did you find a fix for this, besides deleting node_modules every single time ?

**Comment by Raiper34** [comment] 2019-01-21 22:47
> @Raiper34 - did you find a fix for this, besides deleting node_modules every single time ?

I upgrade my project to Angular 7 and with Angular 7 is everything ok :)

**Closed as not planned** 2023-01-24 10:09 UTC
