### ISSUE TITLE
Which version to use in Angular 5

### ISSUE THREAD

**Issue by woj1965** [jodit/jodit-angular#30] opened 2019-03-25 21:41 UTC
Which version can I use with following Angular? I have tried with several versions but I get a lot of errors.

Angular CLI: 1.7.4
Node: 8.15.0
OS: darwin x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cdk: 5.2.4
@angular/cli: 1.7.4
@angular/language-service: 5.2.8
@angular/material: 5.2.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.6.2
webpack: 3.11.0

These are erros I got:
`ERROR in node_modules/jodit-angular/Events.d.ts(2,8): error TS1192: Module '"/Users/wilsondeoliveirajunior/Documents/CP Placas/Software/cp-app/node_modules/jodit/src/types/index"' has no default export.
node_modules/jodit/src/Config.ts(816,12): error TS2352: Type '{ exec: (editor: IJodit) => void; mode: number; }' cannot be converted to type 'IControlType<IJodit | IViewBased<IViewOptions> | IFileBrowser, IToolbarButton>'.
  Types of property 'mode' are incompatible.
    Type 'number' is not comparable to type 'Modes'.
node_modules/jodit/src/Config.ts(853,12): error TS2352: Type '{ exec: (editor: IJodit) => void; tooltip: string; mode: number; }' cannot be converted to type 'IControlType<IJodit | IViewBased<IViewOptions> | IFileBrowser, IToolbarButton>'.
  Types of property 'mode' are incompatible.
    Type 'number' is not comparable to type 'Modes'.
node_modules/jodit/src/modules/Dom.ts(278,27): error TS2304: Cannot find name 'unknown'.
node_modules/jodit/src/modules/Dom.ts(297,24): error TS2304: Cannot find name 'unknown'.
node_modules/jodit/src/modules/Dom.ts(308,25): error TS2304: Cannot find name 'unknown'.
node_modules/jodit/src/modules/Dom.ts(323,26): error TS2304: Cannot find name 'unknown'.
node_modules/jodit/src/modules/Dom.ts(337,32): error TS2304: Cannot find name 'unknown'.
node_modules/jodit/src/modules/Plugin.ts(23,5): error TS2424: Class 'Component<IJodit>' defines instance member function 'destruct', but extended class 'Plugin' defines it as instance member property.
node_modules/jodit/src/modules/Selection.ts(90,30): error TS2304: Cannot find name 'CaretPosition'.
node_modules/jodit/src/modules/Uploader.ts(201,45): error TS2345: Argument of type 'IViewBased<IViewOptions> | this' is not assignable to parameter of type 'IViewBased<IViewOptions>'.
  Type 'this' is not assignable to type 'IViewBased<IViewOptions>'.
    Type 'Uploader' is not assignable to type 'IViewBased<IViewOptions>'.
      Property 'id' is missing in type 'Uploader'.
node_modules/jodit/src/modules/dialog/dialog.ts(124,45): error TS2345: Argument of type '(elm: ChildNode) => void' is not assignable to parameter of type '(value: Node, index: number, array: Node[]) => void'.
  Types of parameters 'elm' and 'value' are incompatible.
    Type 'Node' is not assignable to type 'ChildNode'.
      Property 'remove' is missing in type 'Node'.
node_modules/jodit/src/modules/dialog/dialog.ts(126,34): error TS2345: Argument of type 'ChildNode' is not assignable to parameter of type 'Node'.
  Property 'attributes' is missing in type 'ChildNode'.
node_modules/jodit/src/modules/helpers/checker/isJoditObject.ts(14,38): error TS2304: Cannot find name 'unknown'.
node_modules/jodit/src/modules/toolbar/element.ts(76,17): error TS2322: Type 'void | HTMLElement' is not assignable to type 'HTMLElement'.
  Type 'void' is not assignable to type 'HTMLElement'.
node_modules/jodit/src/modules/toolbar/joditToolbarCollection.ts(55,13): error TS2322: Type 'boolean | void' is not assignable to type 'boolean'.
  Type 'void' is not assignable to type 'boolean'.`

**Comment by katan** [comment] 2019-03-26 10:42
Duplicate of #24

**Closed as completed** 2021-03-20 17:19 UTC
